language: node_js
node_js:
  - "8"
  - "10"
dist: trusty
sudo: false

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

install:
  - npm ci

cache:
  directories:
    - node_modules

script:
  # Currently audit via npmjs.org unreliable
  # - npm audit
  - npm run lint
  - npm run test
  - npm run coveralls

after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
