# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
  branches:
    include:
    - master
    - feat/*
    exclude:
    - wip/*

pool:
  vmImage: 'Ubuntu-16.04'

# variables:
# - group: coveralls

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: npm install
  displayName: 'npm install'

# Currently audit via npmjs.org unreliable
# - script: npm audit
#   displayName: 'Dependency Audit'

- script: npm run lint
  displayName: 'Lint Code'

- script: npm run test
  displayName: 'Unit Tests'

# # Does not work - coveralls does not recognize repo, even with token
# - script: npm run coveralls
#   displayName: 'Publish Coverage to Coveralls.io'
#   env:
#     COVERALLS_SERVICE_NAME: 'Azure Pipelines'
#     COVERALLS_SERVICE_JOB_ID: ${Build.BuildId}

# See https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/test/publish-code-coverage-results?view=azure-devops&viewFallbackFrom=vsts
- task: PublishCodeCoverageResults@1
  displayName: 'Save Code Coverage'
  inputs:
    codeCoverageTool: cobertura
    summaryFileLocation: './coverage/cobertura-coverage.xml'
    reportDirectory: './coverage/lcov-report'
    #additionalCodeCoverageFiles: # Optional
    #failIfCoverageEmpty: false # Optional
